export function createInteractiveBookApp() {
    const $ = id => document.getElementById(id);
    const els = {
        canvas: $('bookCanvas'),
        bookStage: $('book-stage'),
        bookTabs: $('book-tabs'),
        bookTitleInput: $('book-title-input'),
        bookDescriptionInput: $('book-description-input'),
        addBookButton: $('add-book-button'),
        bookStyleSelect: $('book-style-select'),
        fileUpload: $('file-upload'),
        contextFileUpload: $('context-file-upload'),
        mediaTray: $('floating-media-tray'),
        mediaTrayTabs: Array.from(document.querySelectorAll('[data-media-tray-tab]')),
        mediaTrayPanels: Array.from(document.querySelectorAll('[data-media-tray-panel]')),
        openMediaTrayButton: $('open-media-tray-button'),
        closeMediaTrayButton: $('close-media-tray-button'),
        resetBookButton: $('reset-book-button'),
        clearAddedPagesButton: $('clear-added-pages-button'),
        sealBookButton: $('seal-book-button'),
        refreshDashboardMediaButton: $('refresh-dashboard-media-button'),
        insertPositionSelect: $('insert-position-select'),
        imagePoolSelect: $('image-pool-select'),
        imagePoolList: $('image-pool-list'),
        recentGeneratedList: $('recent-generated-list'),
        addSelectedPoolImagesButton: $('add-selected-pool-images-button'),
        addSelectedRecentImagesButton: $('add-selected-recent-images-button'),
        addAllPoolImagesButton: $('add-all-pool-images-button'),
        addAllRecentImagesButton: $('add-all-recent-images-button'),
        pageQueue: $('page-queue'),
        bookStatus: $('book-status'),
        pageContextMenu: $('page-context-menu'),
        mediaContextMenu: $('media-context-menu'),
        animationSpeedSelect: $('animation-speed-select'),
        pageFontSizeSelect: $('page-font-size-select'),
        pageBgColorSelect: $('page-bg-color-select'),
        zoomInButton: $('zoom-in-button'),
        zoomOutButton: $('zoom-out-button'),
        zoomResetButton: $('zoom-reset-button'),
        zoomLevelDisplay: $('zoom-level-display'),
        fullscreenButton: $('fullscreen-button'),
        exportBookButton: $('export-book-button'),
        pageCounter: $('page-counter'),
        inspectBookButton: $('inspect-book-button'),
        magnifierButton: $('magnifier-button'),
        magnifierLens: $('book-magnifier-lens'),
        magnifierCanvas: $('book-magnifier-canvas')
    };

    const ctx = els.canvas.getContext('2d');
    const pageWidth = 450;
    const pageHeight = 550;
    const margin = 50;

    els.canvas.width = (pageWidth * 2) + (margin * 2);
    els.canvas.height = pageHeight + (margin * 2);

    const basePages = [
        { bg: 'transparent', isVoid: true },
        { text: 'MY\nJOURNAL', bg: '#4a3728', textColor: '#d4af37', fontSize: 50 },
        { text: 'A collection of\ncaptured moments.', bg: '#fdfbf0', textColor: '#444', fontSize: 22 },
        { type: 'dynamic-placeholder' },
        { text: 'THE END', bg: '#4a3728', textColor: '#d4af37', fontSize: 40 }
    ];

    const bookSkins = {
        inferno: {
            coverBase: '#a91610',
            coverShadow: '#4f0906',
            coverHighlight: '#ff5d2a',
            trim: '#d5a61c',
            trimDark: '#80580f',
            gem: '#ff8d14',
            gemGlow: 'rgba(255,140,32,0.42)',
            pageEdge: '#f0d39d',
            pageShade: '#c99642',
            pageSurface: '#fff1dc',
            stageAccent: '#ff6f32'
        },
        tide: {
            coverBase: '#116f8e',
            coverShadow: '#0a3442',
            coverHighlight: '#2dd8ff',
            trim: '#d3f6ff',
            trimDark: '#5aa7bb',
            gem: '#48f3ff',
            gemGlow: 'rgba(72,243,255,0.34)',
            pageEdge: '#dcf6ff',
            pageShade: '#76b6cf',
            pageSurface: '#effcff',
            stageAccent: '#36c6ff'
        },
        royal: {
            coverBase: '#5a2446',
            coverShadow: '#261021',
            coverHighlight: '#a44a8b',
            trim: '#deb25a',
            trimDark: '#7b541b',
            gem: '#ff5bc6',
            gemGlow: 'rgba(255,91,198,0.34)',
            pageEdge: '#efe0bd',
            pageShade: '#b89459',
            pageSurface: '#fff3dd',
            stageAccent: '#ff82c5'
        }
    };

    const state = {
        bookStyle: 'inferno',
        currentPage: 0,
        progress: 0,
        isAnimating: false,
        isPreparingFlip: false,
        dir: 0,
        books: [],
        activeBookId: '',
        dynamicPages: [],
        prerenderedPages: [],
        prerenderedPageKeys: [],
        imagePools: [],
        recentImages: [],
        selectedPoolImageIds: new Set(),
        selectedRecentImageIds: new Set(),
        mediaTrayTab: 'pools',
        insertPosition: 'end',
        contextMenuPageId: '',
        contextMenuInsertIndex: null,
        pendingUploadAction: null,
        contextMenuMediaItem: null,
        draggingPageId: '',
        mediaElements: new Map(),
        mediaSnapshots: new Map(),
        mediaOverlays: new Map(),
        pendingMediaLoads: new Map(),
        objectUrls: new Set(),
        pageRenderCache: new Map(),
        pagesData: [],
        viewOffsetX: 0,
        renderRequested: false,
        animationStartTime: 0,
        animationDuration: 760,
        slideDuration: 360,
        popDuration: 150,
        closedSpinDuration: 520,
        animationDurationSlow: 1260,
        animationDurationFast: 350,
        animationPhase: 'idle',
        animationPlan: null,
        animationPageCanvases: new Map(),
        animationStartOffset: 0,
        animationTargetOffset: 0,
        animationStartProgressRaw: 0,
        initBookTimer: 0,
        activeRenderToken: 0,
        sealed: false,
        sealIntegrity: 0,
        sealHitTime: 0,
        zoomLevel: 1,
        isClosedBookHovered: false,
        closedBookHoverProgress: 0,
        isCanvasHovered: false,
        inspectMode: false,
        inspectRotationX: 0,
        inspectRotationY: 0,
        inspectTargetRotationX: 0,
        inspectTargetRotationY: 0,
        magnifierEnabled: false,
        magnifierVisible: false,
        magnifierPointerX: 0,
        magnifierPointerY: 0,
        closedSpinFromSide: 'front',
        closedSpinToSide: 'back',
        fontSize: 22,
        bgColor: '#fdfbf0',
        mouseHoldStartTime: 0,
        isMouseHolding: false,
        dragStartX: 0,
        dragStartY: 0,
        isDragging: false,
        dragDirection: 0,
        dragProgress: 0,
        dragPreparedDirection: 0,
        flipSpeed: 'normal',
        mediaTrayDrag: {
            active: false,
            startX: 0,
            startY: 0,
            origLeft: 0,
            origTop: 0,
            pointerId: null,
            handle: null
        }
    };

    return {
        $,
        els,
        ctx,
        pageWidth,
        pageHeight,
        margin,
        basePages,
        bookSkins,
        maxSealIntegrity: 4,
        state
    };
}
