(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={nodes:[],groups:[],edges:[],selected:null,mode:'select',zoom:0.82,panX:35,panY:20,snap:true,grid:true,history:[],future:[],drag:null,connect:null,z:20,title:'URage Studio — System Architecture'};
const COLORS=['#6d5dfc','#2563eb','#0ea5e9','#16a34a','#f59e0b','#ef4444','#64748b','#111827'];
const ICONS={
 user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="7" r="4"/><path d="M2.5 21v-2a6.5 6.5 0 0 1 13 0v2"/><path d="M16 4.5a3.7 3.7 0 0 1 0 7M17 14.2c2.6.9 4.5 3.4 4.5 6.3"/></svg>',
 bot:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="7" width="16" height="12" rx="3"/><path d="M12 3v4M8 12h.01M16 12h.01M8 16h8"/></svg>',
 telegram:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M21.7 3.4 18.5 19c-.2 1.1-.9 1.4-1.8.9l-4.9-3.6-2.4 2.3c-.3.3-.5.5-1 .5l.4-5 9.1-8.2c.4-.4-.1-.6-.6-.2L6 12.8l-4.8-1.5c-1-.3-1.1-1 .2-1.5L20 2.6c.9-.3 1.7.2 1.7.8Z"/></svg>',
 braces:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M8 3H5v18h3M16 3h3v18h-3"/><path d="M10 15V9l2 4 2-4v6"/></svg>',
 display:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
 gear:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6V21h-4v-.1a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H3v-4h.1a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6V3h4v.1a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1H21v4h-.1a1.7 1.7 0 0 0-1.5 1Z"/></svg>',
 database:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg>',
 layers:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></svg>',
 cloud:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17.5 19H7a5 5 0 0 1-.5-10A6.5 6.5 0 0 1 19 10.8 4.2 4.2 0 0 1 17.5 19Z"/></svg>',
 code:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/></svg>',
 cube:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg>',
 folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 6h7l2 2h9v11H3V6Z"/></svg>',
 share:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="6" cy="12" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="18" cy="18" r="2"/><path d="m8 11 8-4M8 13l8 4"/></svg>',
 terminal:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3M12 15h5"/></svg>',
 note:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 3h14v14l-4 4H5V3Z"/><path d="M15 21v-4h4M8 8h8M8 12h6"/></svg>'
};
const TYPES=[
 ['service','Service','gear'],['database','Database','database'],['queue','Queue','layers'],['bot','Bot','bot'],['user','User','user'],['cloud','Cloud','cloud'],['api','API / Code','code'],['worker','Worker','terminal'],['storage','Storage','folder'],['3d','3D / Render','cube']
];
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function clone(o){return JSON.parse(JSON.stringify(o))}
function icon(name){return ICONS[name]||ICONS.gear}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>e.classList.remove('show'),1500)}
function snap(v){return S.snap?Math.round(v/22)*22:v}
function snapshot(){return JSON.stringify({nodes:S.nodes,groups:S.groups,edges:S.edges,title:S.title})} function pushHistory(raw=snapshot()){S.history.push(raw);if(S.history.length>60)S.history.shift();S.future=[];updateUndo()}
function restore(raw){const o=JSON.parse(raw);S.nodes=o.nodes||[];S.groups=o.groups||[];S.edges=o.edges||[];S.title=o.title||S.title;$('#docTitle').value=S.title;S.selected=null;renderAll()}
function undo(){if(!S.history.length)return;S.future.push(JSON.stringify({nodes:S.nodes,groups:S.groups,edges:S.edges,title:S.title}));restore(S.history.pop());updateUndo()}
function redo(){if(!S.future.length)return;S.history.push(JSON.stringify({nodes:S.nodes,groups:S.groups,edges:S.edges,title:S.title}));restore(S.future.pop());updateUndo()}
function updateUndo(){$('#undoBtn').disabled=!S.history.length;$('#redoBtn').disabled=!S.future.length}
function defaultDemo(){
 S.nodes=[
 {id:'users',x:1035,y:58,w:330,title:'Users',subtitle:'Chat / Commands / Requests',details:[],footer:'',color:'#111827',icon:'user',kind:'compact',z:12},
 {id:'discord',x:315,y:240,w:285,title:'Discord Bot',subtitle:'',details:['Slash Commands','Message Handling','Events / Interactions'],footer:'bots/discord-bot',color:'#6d5dfc',icon:'bot',kind:'service',z:12},
 {id:'telegram',x:710,y:240,w:285,title:'Telegram Bot',subtitle:'',details:['Commands','Message Handling','Events / Interactions'],footer:'bots/telegram-bot',color:'#0ea5e9',icon:'telegram',kind:'service',z:12},
 {id:'matrix',x:1105,y:240,w:285,title:'Matrix Bot',subtitle:'',details:['Commands','Message Handling','Events / Interactions'],footer:'bots/matrix-bot',color:'#16a34a',icon:'braces',kind:'service',z:12},
 {id:'dashboard',x:315,y:575,w:320,title:'Dashboard (Web UI)',subtitle:'',details:['Runtime Control','Bot Management','Theme Management','Logs & Monitoring','Settings'],footer:'dashboard/src',color:'#2563eb',icon:'display',kind:'service',z:12},
 {id:'api',x:710,y:575,w:250,title:'API Server',subtitle:'',details:['REST API','WebSocket','Auth & Roles','Runtime Control'],footer:'',color:'#2563eb',icon:'gear',kind:'service',z:12},
 {id:'db',x:1010,y:575,w:230,title:'Database',subtitle:'SQLite',details:['Settings','Users / Roles','Themes','Logs','Runtime State'],footer:'',color:'#2563eb',icon:'database',kind:'service',z:12},
 {id:'queue',x:1290,y:575,w:250,title:'Task Queue',subtitle:'BullMQ',details:['Generation Jobs','Status Tracking','Retries / Failures'],footer:'',color:'#2563eb',icon:'layers',kind:'service',z:12},
 {id:'remote',x:1665,y:250,w:300,title:'Remote Generation Workers',subtitle:'',details:['Process Generation Tasks','Scale Out Workloads'],footer:'workers/remote-worker',color:'#7c3aed',icon:'terminal',kind:'service',z:12},
 {id:'comfy',x:595,y:990,w:325,title:'ComfyUI',subtitle:'AI Image / Video / Audio Generation',details:['Workflows','Models','LoRAs / Embeddings','Outputs'],footer:'Local or Remote',color:'#16a34a',icon:'share',kind:'service',z:12},
 {id:'blender',x:1085,y:990,w:325,title:'Blender',subtitle:'3D Model / Animation Generation',details:['Python Scripts','Scene Automation','Rendering','Outputs (GLB / FBX / Images)'],footer:'blender-scripts/',color:'#f59e0b',icon:'cube',kind:'service',z:12},
 {id:'storage',x:600,y:1325,w:805,title:'Storage & Assets',subtitle:'Generated Files · Models / Checkpoints · Textures / Materials',details:['Themes (JSON)','User Uploads','Logs'],footer:'data/',color:'#f59e0b',icon:'folder',kind:'compact',z:12}
 ];
 S.groups=[
 {id:'gmsg',x:250,y:185,w:1210,h:275,title:'Messengers (Runtimes)',color:'#7c3aed',z:1},
 {id:'gback',x:250,y:515,w:1355,h:310,title:'Dashboard & Backend',color:'#2563eb',z:1},
 {id:'gremote',x:1615,y:180,w:405,h:285,title:'Remote Workers (Optional)',color:'#7c3aed',z:1},
 {id:'ggen',x:545,y:920,w:930,h:300,title:'Generation Pipeline',color:'#16a34a',z:1},
 {id:'gstore',x:545,y:1275,w:930,h:210,title:'Storage & Assets',color:'#f59e0b',z:1}
 ];
 S.edges=[
 ['e1','users','discord','request','orthogonal','end',''],['e2','users','telegram','request','orthogonal','end',''],['e3','users','matrix','request','orthogonal','end',''],
 ['e4','discord','api','request','orthogonal','both',''],['e5','telegram','api','request','orthogonal','both',''],['e6','matrix','api','request','orthogonal','both',''],
 ['e7','dashboard','api','request','straight','both',''],['e8','api','db','request','straight','both',''],['e9','db','queue','request','straight','both',''],
 ['e10','queue','remote','job','orthogonal','end',''],['e11','queue','blender','job','orthogonal','end',''],['e12','comfy','blender','data','straight','both','Data / Assets Exchange'],
 ['e13','storage','comfy','generation','orthogonal','end',''],['e14','storage','blender','generation','orthogonal','end','']
 ].map(([id,from,to,style,route,arrow,label])=>({id,from,to,style,route,arrow,label}));
 S.title='URage Studio — System Architecture';S.z=30;S.selected=null;S.history=[];S.future=[];
}
function renderPalette(){const p=$('#palette');p.innerHTML=TYPES.map(([type,label,ic])=>`<div class="palette-item" draggable="true" data-type="${type}" data-icon="${ic}"><div class="palette-icon">${icon(ic)}</div><div class="palette-label">${label}</div></div>`).join('');$$('.palette-item').forEach(el=>el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/flowcraft',JSON.stringify({type:el.dataset.type,icon:el.dataset.icon}));e.dataTransfer.effectAllowed='copy'}));$('#swatches').innerHTML=COLORS.map(c=>`<button class="swatch" style="--c:${c}" data-color="${c}" title="${c}"></button>`).join('');}
function newNode(type='service',iconName='gear',x=700,y=420){let title={database:'Database',queue:'Task Queue',bot:'Bot Runtime',user:'Users',cloud:'Cloud Service',api:'API Service',worker:'Worker',storage:'Storage', '3d':'Render / 3D'}[type]||'New Service';let kind=type==='user'?'compact':'service';return{id:uid('n'),x:snap(x),y:snap(y),w:276,title,subtitle:'',details:['Capability one','Capability two'],footer:'',color:'#2563eb',icon:iconName,kind,z:++S.z}}
function nodeHeight(n){if(n.kind==='note')return Math.max(105,70+(n.details.join('\n').length/32)*16);if(n.kind==='compact')return 88+(n.details.length?Math.min(2,n.details.length)*16:0);return 92+n.details.length*16+(n.footer?28:0)+(n.subtitle?7:0)}
function renderNodes(){const layer=$('#nodeLayer');layer.innerHTML='';S.nodes.forEach(n=>{const el=document.createElement('div');el.className='node '+(n.kind||'service')+(S.selected?.type==='node'&&S.selected.id===n.id?' selected':'')+(S.connect?.from===n.id?' connect-source':'');el.dataset.id=n.id;el.style.cssText=`left:${n.x}px;top:${n.y}px;width:${n.w}px;--c:${n.color};z-index:${n.z||10}`;const body=n.kind==='note'?`<div class="node-main"><div class="node-copy"><div class="node-title">${esc(n.title)}</div><div class="node-list">${esc(n.details.join('\n'))}</div></div></div>`:`<div class="node-main"><div class="node-icon">${icon(n.icon)}</div><div class="node-copy"><div class="node-title">${esc(n.title)}</div>${n.subtitle?`<div class="node-sub">${esc(n.subtitle)}</div>`:''}${n.details.length?`<ul class="node-list">${n.details.map(d=>`<li>${esc(d)}</li>`).join('')}</ul>`:''}</div></div>${n.footer?`<div class="node-footer"><span class="pill">${esc(n.footer)}</span></div>`:''}`;el.innerHTML=body+['t','r','b','l'].map(p=>`<div class="port ${p}" data-port="${p}"></div>`).join('');layer.appendChild(el);wireNode(el,n)});}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderGroups(){const l=$('#groupLayer');l.innerHTML='';S.groups.forEach(g=>{const el=document.createElement('div');el.className='group'+(S.selected?.type==='group'&&S.selected.id===g.id?' selected':'');el.dataset.id=g.id;el.style.cssText=`left:${g.x}px;top:${g.y}px;width:${g.w}px;height:${g.h}px;--c:${g.color};z-index:${g.z||1}`;el.innerHTML=`<div class="group-head">${esc(g.title)}</div><div class="group-resize"></div>`;l.appendChild(el);wireGroup(el,g)});}
function center(n){return{x:n.x+n.w/2,y:n.y+nodeHeight(n)/2}}
function ports(n){const h=nodeHeight(n);return{t:{x:n.x+n.w/2,y:n.y},r:{x:n.x+n.w,y:n.y+h/2},b:{x:n.x+n.w/2,y:n.y+h},l:{x:n.x,y:n.y+h/2}}}
function choosePorts(a,b){const ac=center(a),bc=center(b),dx=bc.x-ac.x,dy=bc.y-ac.y;if(Math.abs(dx)>Math.abs(dy))return dx>0?['r','l']:['l','r'];return dy>0?['b','t']:['t','b']}
function edgePath(e){const a=S.nodes.find(n=>n.id===e.from),b=S.nodes.find(n=>n.id===e.to);if(!a||!b)return{d:'',mid:{x:0,y:0},sp:'r',tp:'l'};const [sp,tp]=choosePorts(a,b),A=ports(a)[sp],B=ports(b)[tp];if(e.route==='straight')return{d:`M${A.x},${A.y} L${B.x},${B.y}`,mid:{x:(A.x+B.x)/2,y:(A.y+B.y)/2},sp,tp};if(e.route==='curve'){const horiz=sp==='r'||sp==='l',c1=horiz?{x:(A.x+B.x)/2,y:A.y}:{x:A.x,y:(A.y+B.y)/2},c2=horiz?{x:(A.x+B.x)/2,y:B.y}:{x:B.x,y:(A.y+B.y)/2};return{d:`M${A.x},${A.y} C${c1.x},${c1.y} ${c2.x},${c2.y} ${B.x},${B.y}`,mid:{x:(A.x+B.x)/2,y:(A.y+B.y)/2},sp,tp};}if(sp==='r'||sp==='l'){const mx=(A.x+B.x)/2;return{d:`M${A.x},${A.y} L${mx},${A.y} L${mx},${B.y} L${B.x},${B.y}`,mid:{x:mx,y:(A.y+B.y)/2},sp,tp}}const my=(A.y+B.y)/2;return{d:`M${A.x},${A.y} L${A.x},${my} L${B.x},${my} L${B.x},${B.y}`,mid:{x:(A.x+B.x)/2,y:my},sp,tp}}
function marker(style){return style==='job'?'#aViolet':style==='generation'?'#aGreen':style==='data'?'#aCyan':'#aBlack'}
function renderEdges(){const g=$('#edges');g.innerHTML='';S.edges.forEach(e=>{const p=edgePath(e);if(!p.d)return;const wrap=document.createElementNS('http://www.w3.org/2000/svg','g');wrap.dataset.id=e.id;const hit=document.createElementNS('http://www.w3.org/2000/svg','path');hit.setAttribute('d',p.d);hit.setAttribute('class','edge-hit');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',p.d);path.setAttribute('class','edge '+e.style+(S.selected?.type==='edge'&&S.selected.id===e.id?' selected':''));if(e.arrow==='end'||e.arrow==='both')path.setAttribute('marker-end',`url(${marker(e.style)})`);if(e.arrow==='both')path.setAttribute('marker-start',`url(${marker(e.style)})`);if(e.label){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',p.mid.x);t.setAttribute('y',p.mid.y-8);t.setAttribute('text-anchor','middle');t.setAttribute('class','edge-label');t.textContent=e.label;wrap.appendChild(t)}wrap.insertBefore(path,wrap.firstChild);wrap.insertBefore(hit,wrap.firstChild);g.appendChild(wrap);hit.addEventListener('pointerdown',ev=>{ev.stopPropagation();select('edge',e.id)});hit.addEventListener('contextmenu',ev=>{ev.preventDefault();ev.stopPropagation();select('edge',e.id);showContext(ev.clientX,ev.clientY)})});}
function renderMini(){const svg=$('#miniSvg');let s='<rect width="3200" height="2200" fill="transparent"/>';S.groups.forEach(g=>s+=`<rect x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}" rx="16" fill="${g.color}16" stroke="${g.color}" stroke-width="7"/>`);S.nodes.forEach(n=>s+=`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${nodeHeight(n)}" rx="10" fill="${n.color}35" stroke="${n.color}" stroke-width="5"/>`);const vp=$('#viewport').getBoundingClientRect(),vx=(-S.panX/S.zoom),vy=(-S.panY/S.zoom),vw=vp.width/S.zoom,vh=vp.height/S.zoom;s+=`<rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" fill="none" stroke="#2563eb" stroke-width="10"/>`;svg.innerHTML=s}
function renderAll(){renderGroups();renderEdges();renderNodes();renderInspector();applyTransform();renderMini();updateStatus();updateUndo()}
function applyTransform(){const c=$('#canvas');c.style.transform=`translate(${S.panX}px,${S.panY}px) scale(${S.zoom})`;$('#zoomLabel').textContent=Math.round(S.zoom*100)+'%';$('#viewport').classList.toggle('no-grid',!S.grid);$('#gridBtn').classList.toggle('active',S.grid);$('#snapBtn').classList.toggle('active',S.snap);renderMini()}
function updateStatus(){const mode=S.mode[0].toUpperCase()+S.mode.slice(1);$('#status').textContent=`${mode} mode · ${S.nodes.length} nodes · ${S.edges.length} connections`}
function select(type,id){S.selected={type,id};renderNodes();renderGroups();renderEdges();renderInspector()}
function clearSelection(){S.selected=null;renderNodes();renderGroups();renderEdges();renderInspector()}
function renderInspector(){const all=['#emptyInspector','#nodeInspector','#edgeInspector','#groupInspector'];all.forEach(s=>$(s).classList.add('hidden'));if(!S.selected){$('#emptyInspector').classList.remove('hidden');return}if(S.selected.type==='node'){const n=S.nodes.find(x=>x.id===S.selected.id);if(!n)return clearSelection();$('#nodeInspector').classList.remove('hidden');$('#nodeTitleInput').value=n.title;$('#nodeSubInput').value=n.subtitle;$('#nodeDetailsInput').value=n.details.join('\n');$('#nodeFooterInput').value=n.footer;$('#nodeColorInput').value=n.color;$('#nodeIconInput').value=n.icon;$('#nodeWInput').value=n.w;$('#nodeKindInput').value=n.kind||'service'}else if(S.selected.type==='edge'){const e=S.edges.find(x=>x.id===S.selected.id);if(!e)return clearSelection();$('#edgeInspector').classList.remove('hidden');$('#edgeLabelInput').value=e.label||'';$('#edgeStyleInput').value=e.style;$('#edgeRouteInput').value=e.route;$('#edgeArrowInput').value=e.arrow}else{const g=S.groups.find(x=>x.id===S.selected.id);if(!g)return clearSelection();$('#groupInspector').classList.remove('hidden');$('#groupTitleInput').value=g.title;$('#groupColorInput').value=g.color;$('#groupWInput').value=g.w;$('#groupHInput').value=g.h}}
function clientToCanvas(cx,cy){const r=$('#viewport').getBoundingClientRect();return{x:(cx-r.left-S.panX)/S.zoom,y:(cy-r.top-S.panY)/S.zoom}}
function wireNode(el,n){el.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.stopPropagation();if(e.target.classList.contains('port')){startConnect(n.id,e.clientX,e.clientY);return}if(S.mode==='connect'){if(!S.connect)startConnect(n.id,e.clientX,e.clientY);else finishConnect(n.id);return}select('node',n.id);const p=clientToCanvas(e.clientX,e.clientY);S.drag={kind:'node',id:n.id,dx:p.x-n.x,dy:p.y-n.y,moved:false,before:snapshot()};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(S.drag?.kind==='node'&&S.drag.id===n.id){const p=clientToCanvas(e.clientX,e.clientY);n.x=snap(p.x-S.drag.dx);n.y=snap(p.y-S.drag.dy);S.drag.moved=true;renderEdges();el.style.left=n.x+'px';el.style.top=n.y+'px';renderMini()}});el.addEventListener('pointerup',e=>{if(S.drag?.kind==='node'&&S.drag.id===n.id){if(S.drag.moved)pushHistory(S.drag.before);S.drag=null}});el.addEventListener('dblclick',()=>{select('node',n.id);$('#nodeTitleInput').focus();$('#nodeTitleInput').select()});el.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();select('node',n.id);showContext(e.clientX,e.clientY)})}
function wireGroup(el,g){el.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.stopPropagation();select('group',g.id);const p=clientToCanvas(e.clientX,e.clientY);if(e.target.classList.contains('group-resize'))S.drag={kind:'resize-group',id:g.id,ox:p.x,oy:p.y,ow:g.w,oh:g.h,before:snapshot(),moved:false};else S.drag={kind:'group',id:g.id,dx:p.x-g.x,dy:p.y-g.y,before:snapshot(),moved:false};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!S.drag||S.drag.id!==g.id)return;const p=clientToCanvas(e.clientX,e.clientY);S.drag.moved=true;if(S.drag.kind==='group'){g.x=snap(p.x-S.drag.dx);g.y=snap(p.y-S.drag.dy);el.style.left=g.x+'px';el.style.top=g.y+'px'}else if(S.drag.kind==='resize-group'){g.w=Math.max(180,snap(S.drag.ow+p.x-S.drag.ox));g.h=Math.max(120,snap(S.drag.oh+p.y-S.drag.oy));el.style.width=g.w+'px';el.style.height=g.h+'px'}renderMini()});el.addEventListener('pointerup',()=>{if(S.drag?.id===g.id){if(S.drag.moved)pushHistory(S.drag.before);S.drag=null}});el.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();select('group',g.id);showContext(e.clientX,e.clientY)})}
function startConnect(id,cx,cy){S.mode='connect';setMode('connect');S.connect={from:id};renderNodes();updateDraft(cx,cy);showToast('Click another node to connect')}
function finishConnect(to){if(!S.connect||to===S.connect.from){S.connect=null;$('#draftEdge').setAttribute('d','');renderNodes();return}pushHistory();S.edges.push({id:uid('e'),from:S.connect.from,to,style:'request',route:'orthogonal',arrow:'end',label:''});S.connect=null;$('#draftEdge').setAttribute('d','');setMode('select');renderAll()}
function updateDraft(cx,cy){if(!S.connect)return;const n=S.nodes.find(x=>x.id===S.connect.from);if(!n)return;const p=clientToCanvas(cx,cy),c=center(n);$('#draftEdge').setAttribute('d',`M${c.x},${c.y} L${p.x},${p.y}`)}
function setMode(m){S.mode=m;$$('#modeSeg button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));document.body.classList.toggle('connect-mode',m==='connect');$('#viewport').classList.toggle('pan-mode',m==='pan');updateStatus()}
function addNodeAt(type,ic,x,y){pushHistory();const n=newNode(type,ic,x,y);S.nodes.push(n);select('node',n.id);renderAll()}
function duplicateSelected(){if(!S.selected)return;pushHistory();if(S.selected.type==='node'){const n=clone(S.nodes.find(x=>x.id===S.selected.id));n.id=uid('n');n.x+=35;n.y+=35;n.title+=' Copy';n.z=++S.z;S.nodes.push(n);S.selected={type:'node',id:n.id}}else if(S.selected.type==='group'){const g=clone(S.groups.find(x=>x.id===S.selected.id));g.id=uid('g');g.x+=40;g.y+=40;g.title+=' Copy';S.groups.push(g);S.selected={type:'group',id:g.id}}renderAll()}
function deleteSelected(){if(!S.selected)return;pushHistory();if(S.selected.type==='node'){const id=S.selected.id;S.nodes=S.nodes.filter(n=>n.id!==id);S.edges=S.edges.filter(e=>e.from!==id&&e.to!==id)}else if(S.selected.type==='edge')S.edges=S.edges.filter(e=>e.id!==S.selected.id);else S.groups=S.groups.filter(g=>g.id!==S.selected.id);S.selected=null;renderAll()}
function zMove(dir){if(!S.selected)return;if(S.selected.type==='node'){const n=S.nodes.find(x=>x.id===S.selected.id);n.z=dir>0?++S.z:Math.max(2,(n.z||10)-2)}else if(S.selected.type==='group'){const g=S.groups.find(x=>x.id===S.selected.id);g.z=dir>0?Math.min(4,(g.z||1)+1):Math.max(0,(g.z||1)-1)}renderAll()}
function fitView(){const items=[...S.nodes.map(n=>({x:n.x,y:n.y,w:n.w,h:nodeHeight(n)})),...S.groups.map(g=>({x:g.x,y:g.y,w:g.w,h:g.h}))];if(!items.length){S.zoom=1;S.panX=20;S.panY=20;applyTransform();return}const minX=Math.min(...items.map(i=>i.x)),minY=Math.min(...items.map(i=>i.y)),maxX=Math.max(...items.map(i=>i.x+i.w)),maxY=Math.max(...items.map(i=>i.y+i.h));const vp=$('#viewport').getBoundingClientRect(),pad=80;S.zoom=Math.max(.18,Math.min(1.15,Math.min((vp.width-pad)/(maxX-minX),(vp.height-pad)/(maxY-minY))));S.panX=(vp.width-(maxX-minX)*S.zoom)/2-minX*S.zoom;S.panY=(vp.height-(maxY-minY)*S.zoom)/2-minY*S.zoom;applyTransform()}
function showContext(x,y){const c=$('#context');c.style.left=x+'px';c.style.top=y+'px';c.classList.add('show')}
function hideMenus(){$$('.context').forEach(c=>c.classList.remove('show'))}
function bindInput(id,fn){$(id).addEventListener('input',()=>{fn();renderNodes();renderGroups();renderEdges();renderMini()});$(id).addEventListener('change',pushHistory)}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},100)}
function exportJSON(){const data={version:1,title:S.title,nodes:S.nodes,groups:S.groups,edges:S.edges};download((slug(S.title)||'flowchart')+'.json',new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));showToast('JSON exported')}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function svgMarkup(){const items=[...S.nodes.map(n=>({x:n.x,y:n.y,w:n.w,h:nodeHeight(n)})),...S.groups.map(g=>({x:g.x,y:g.y,w:g.w,h:g.h}))];const minX=Math.min(...items.map(i=>i.x),0)-40,minY=Math.min(...items.map(i=>i.y),0)-40,maxX=Math.max(...items.map(i=>i.x+i.w),1000)+40,maxY=Math.max(...items.map(i=>i.y+i.h),700)+40;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="${maxX-minX}" height="${maxY-minY}" viewBox="${minX} ${minY} ${maxX-minX} ${maxY-minY}"><rect x="${minX}" y="${minY}" width="${maxX-minX}" height="${maxY-minY}" fill="#f7f9fc"/><defs><marker id="arr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#172033"/></marker></defs>`;S.groups.forEach(g=>out+=`<rect x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}" rx="15" fill="${g.color}0d" stroke="${g.color}" stroke-width="1.5"/><text x="${g.x+14}" y="${g.y+27}" font-family="Arial" font-size="11" font-weight="700" fill="${g.color}">${esc(g.title)}</text>`);S.edges.forEach(e=>{const p=edgePath(e);out+=`<path d="${p.d}" fill="none" stroke="${e.style==='job'?'#7c3aed':e.style==='generation'?'#16a34a':e.style==='data'?'#0ea5e9':'#172033'}" stroke-width="1.7" ${e.style==='job'?'stroke-dasharray="8 6"':''} marker-end="url(#arr)"/>`;if(e.label)out+=`<text x="${p.mid.x}" y="${p.mid.y-8}" text-anchor="middle" font-family="Arial" font-size="10" font-weight="700" fill="#334155">${esc(e.label)}</text>`});S.nodes.forEach(n=>{const h=nodeHeight(n);out+=`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${h}" rx="13" fill="white" stroke="${n.color}" stroke-width="1.25"/><rect x="${n.x+14}" y="${n.y+14}" width="44" height="44" rx="11" fill="${n.color}18"/><text x="${n.x+70}" y="${n.y+31}" font-family="Arial" font-size="14" font-weight="700" fill="#111827">${esc(n.title)}</text>`;if(n.subtitle)out+=`<text x="${n.x+70}" y="${n.y+47}" font-family="Arial" font-size="10" fill="#475569">${esc(n.subtitle)}</text>`;n.details.forEach((d,i)=>out+=`<text x="${n.x+70}" y="${n.y+64+i*15}" font-family="Arial" font-size="10" fill="#1f2937">• ${esc(d)}</text>`);});return out+'</svg>'}
function exportSVG(){download((slug(S.title)||'flowchart')+'.svg',new Blob([svgMarkup()],{type:'image/svg+xml'}));showToast('SVG exported')}
function exportPNG(){const svg=svgMarkup(),blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=Math.min(img.width,6000);c.height=Math.min(img.height,4000);const ctx=c.getContext('2d');ctx.fillStyle='#f7f9fc';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download((slug(S.title)||'flowchart')+'.png',b),'image/png');URL.revokeObjectURL(url);showToast('PNG exported')};img.src=url}
function saveLocal(){localStorage.setItem('flowcraft-pro',JSON.stringify({version:1,title:S.title,nodes:S.nodes,groups:S.groups,edges:S.edges}));showToast('Saved in this browser')}
function applyDashboardTheme(payload){
 const theme=String(payload?.theme||'fire').trim()||'fire',tokens=payload?.tokens||{};
 document.body.dataset.dashboardTheme=theme;document.body.classList.remove('dark');document.body.classList.add('dashboard-theme');
 const cssTokens={"--bg":tokens.bg,"--panel":tokens.surface,"--panel2":tokens.surfaceStrong,"--ink":tokens.text,"--muted":tokens.muted,"--line":tokens.line,"--line2":tokens.lineStrong,"--blue":tokens.accent,"--violet":tokens.accentStrong};
 Object.entries(cssTokens).forEach(([property,value])=>{if(typeof value==='string'&&value.trim())document.documentElement.style.setProperty(property,value)});
}

window.addEventListener('message',event=>{
 const message=event?.data||null;
 if(!message||message.source!=='urage-dashboard'||message.type!=='tool:theme')return;
 applyDashboardTheme(message.payload);
});
window.parent?.postMessage({source:'urage-tool',type:'tool:theme-request'},'*');

function loadLocal(){const x=localStorage.getItem('flowcraft-pro');if(!x)return showToast('No local save yet');pushHistory();restore(x);showToast('Local save loaded')}
function fitGroup(){if(S.selected?.type!=='group')return;const g=S.groups.find(x=>x.id===S.selected.id),inside=S.nodes.filter(n=>{const c=center(n);return c.x>g.x&&c.x<g.x+g.w&&c.y>g.y&&c.y<g.y+g.h});if(!inside.length)return showToast('No nodes inside this group');pushHistory();const minX=Math.min(...inside.map(n=>n.x)),minY=Math.min(...inside.map(n=>n.y)),maxX=Math.max(...inside.map(n=>n.x+n.w)),maxY=Math.max(...inside.map(n=>n.y+nodeHeight(n)));g.x=minX-55;g.y=minY-55;g.w=maxX-minX+110;g.h=maxY-minY+110;renderAll()}
function init(){
 renderPalette();$('#nodeIconInput').innerHTML=Object.keys(ICONS).map(k=>`<option value="${k}">${k}</option>`).join('');
 $('#undoBtn').innerHTML=icon('share');$('#undoBtn').style.transform='scaleX(-1)';$('#redoBtn').innerHTML=icon('share');$('#themeBtn').innerHTML='◐';
 defaultDemo();renderAll();setTimeout(fitView,50);
 const vp=$('#viewport');vp.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'});vp.addEventListener('drop',e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/flowcraft');if(!raw)return;const d=JSON.parse(raw),p=clientToCanvas(e.clientX,e.clientY);addNodeAt(d.type,d.icon,p.x-130,p.y-55)});
 vp.addEventListener('pointerdown',e=>{hideMenus();if(e.button!==0)return;if(S.mode==='pan'||e.buttons===4||e.altKey||spaceDown){S.drag={kind:'pan',x:e.clientX,y:e.clientY,px:S.panX,py:S.panY};vp.classList.add('panning');vp.setPointerCapture(e.pointerId)}else{clearSelection();S.drag={kind:'marquee',x:e.clientX,y:e.clientY};const p=clientToCanvas(e.clientX,e.clientY);Object.assign($('#marquee').style,{display:'block',left:p.x+'px',top:p.y+'px',width:'0px',height:'0px'});}});
 vp.addEventListener('pointermove',e=>{if(S.connect)updateDraft(e.clientX,e.clientY);if(S.drag?.kind==='pan'){S.panX=S.drag.px+e.clientX-S.drag.x;S.panY=S.drag.py+e.clientY-S.drag.y;applyTransform()}else if(S.drag?.kind==='marquee'){const a=clientToCanvas(S.drag.x,S.drag.y),b=clientToCanvas(e.clientX,e.clientY),x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);Object.assign($('#marquee').style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'})}});
 vp.addEventListener('pointerup',()=>{vp.classList.remove('panning');if(S.drag?.kind==='marquee')$('#marquee').style.display='none';S.drag=null});vp.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();const old=S.zoom;S.zoom=Math.max(.18,Math.min(2.2,S.zoom*(e.deltaY<0?1.1:.9)));const r=vp.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;S.panX=mx-(mx-S.panX)*(S.zoom/old);S.panY=my-(my-S.panY)*(S.zoom/old);applyTransform()}},{passive:false});
 $$('#modeSeg button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#zoomInBtn').onclick=()=>{S.zoom=Math.min(2.2,S.zoom*1.12);applyTransform()};$('#zoomOutBtn').onclick=()=>{S.zoom=Math.max(.18,S.zoom/1.12);applyTransform()};$('#fitBtn').onclick=fitView;$('#gridBtn').onclick=()=>{S.grid=!S.grid;applyTransform()};$('#snapBtn').onclick=()=>{S.snap=!S.snap;applyTransform()};$('#frontBtn').onclick=()=>zMove(1);$('#backBtn').onclick=()=>zMove(-1);
 $('#addGroupBtn').onclick=()=>{pushHistory();const p=clientToCanvas(innerWidth/2,innerHeight/2);const g={id:uid('g'),x:snap(p.x-240),y:snap(p.y-140),w:480,h:280,title:'New Group',color:'#7c3aed',z:1};S.groups.push(g);select('group',g.id);renderAll()};$('#addNoteBtn').onclick=()=>{const p=clientToCanvas(innerWidth/2,innerHeight/2);pushHistory();const n=newNode('service','note',p.x-130,p.y-70);Object.assign(n,{title:'Note',details:['Double-click or use the inspector to edit this note.'],kind:'note',color:'#f59e0b'});S.nodes.push(n);select('node',n.id);renderAll()};$('#addTextBtn').onclick=()=>{const p=clientToCanvas(innerWidth/2,innerHeight/2);pushHistory();const n=newNode('service','note',p.x-130,p.y-70);Object.assign(n,{title:'Section label',details:[],kind:'compact',icon:'note',color:'#64748b'});S.nodes.push(n);select('node',n.id);renderAll()};
 $$('.swatch').forEach(b=>b.onclick=()=>{if(!S.selected)return;pushHistory();if(S.selected.type==='node')S.nodes.find(n=>n.id===S.selected.id).color=b.dataset.color;if(S.selected.type==='group')S.groups.find(g=>g.id===S.selected.id).color=b.dataset.color;renderAll()});
 $('#dupBtn').onclick=duplicateSelected;$('#delBtn').onclick=deleteSelected;$('#delEdgeBtn').onclick=deleteSelected;$('#delGroupBtn').onclick=deleteSelected;$('#groupFitBtn').onclick=fitGroup;$('#reverseBtn').onclick=()=>{const e=S.edges.find(x=>x.id===S.selected?.id);if(!e)return;pushHistory();[e.from,e.to]=[e.to,e.from];renderAll()};
 bindInput('#nodeTitleInput',()=>S.nodes.find(n=>n.id===S.selected.id).title=$('#nodeTitleInput').value);bindInput('#nodeSubInput',()=>S.nodes.find(n=>n.id===S.selected.id).subtitle=$('#nodeSubInput').value);bindInput('#nodeDetailsInput',()=>S.nodes.find(n=>n.id===S.selected.id).details=$('#nodeDetailsInput').value.split('\n').filter(Boolean));bindInput('#nodeFooterInput',()=>S.nodes.find(n=>n.id===S.selected.id).footer=$('#nodeFooterInput').value);bindInput('#nodeColorInput',()=>S.nodes.find(n=>n.id===S.selected.id).color=$('#nodeColorInput').value);bindInput('#nodeIconInput',()=>S.nodes.find(n=>n.id===S.selected.id).icon=$('#nodeIconInput').value);bindInput('#nodeWInput',()=>S.nodes.find(n=>n.id===S.selected.id).w=Math.max(120,+$('#nodeWInput').value||276));bindInput('#nodeKindInput',()=>S.nodes.find(n=>n.id===S.selected.id).kind=$('#nodeKindInput').value);
 bindInput('#edgeLabelInput',()=>S.edges.find(e=>e.id===S.selected.id).label=$('#edgeLabelInput').value);bindInput('#edgeStyleInput',()=>S.edges.find(e=>e.id===S.selected.id).style=$('#edgeStyleInput').value);bindInput('#edgeRouteInput',()=>S.edges.find(e=>e.id===S.selected.id).route=$('#edgeRouteInput').value);bindInput('#edgeArrowInput',()=>S.edges.find(e=>e.id===S.selected.id).arrow=$('#edgeArrowInput').value);
 bindInput('#groupTitleInput',()=>S.groups.find(g=>g.id===S.selected.id).title=$('#groupTitleInput').value);bindInput('#groupColorInput',()=>S.groups.find(g=>g.id===S.selected.id).color=$('#groupColorInput').value);bindInput('#groupWInput',()=>S.groups.find(g=>g.id===S.selected.id).w=Math.max(180,+$('#groupWInput').value||300));bindInput('#groupHInput',()=>S.groups.find(g=>g.id===S.selected.id).h=Math.max(120,+$('#groupHInput').value||200));
 $('#docTitle').addEventListener('change',()=>{pushHistory();S.title=$('#docTitle').value});$('#saveBtn').onclick=saveLocal;$('#loadBtn').onclick=loadLocal;$('#resetBtn').onclick=()=>{pushHistory();defaultDemo();renderAll();setTimeout(fitView,30)};$('#clearBtn').onclick=()=>{if(!confirm('Clear the entire diagram?'))return;pushHistory();S.nodes=[];S.groups=[];S.edges=[];S.selected=null;renderAll()};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
 $('#exportBtn').onclick=e=>{e.stopPropagation();const m=$('#exportMenu'),r=e.currentTarget.getBoundingClientRect();m.style.left=(r.right-180)+'px';m.style.top=(r.bottom+6)+'px';m.classList.toggle('show')};$$('#exportMenu button').forEach(b=>b.onclick=async()=>{hideMenus();if(b.dataset.exp==='json')exportJSON();if(b.dataset.exp==='svg')exportSVG();if(b.dataset.exp==='png')exportPNG();if(b.dataset.exp==='copy'){await navigator.clipboard.writeText(JSON.stringify({version:1,title:S.title,nodes:S.nodes,groups:S.groups,edges:S.edges},null,2));showToast('JSON copied')}});
 $('#importBtn').onclick=()=>$('#modalback').classList.add('show');$('#cancelImport').onclick=()=>$('#modalback').classList.remove('show');$('#doImport').onclick=()=>{try{const x=JSON.parse($('#importText').value);pushHistory();S.nodes=x.nodes||[];S.groups=x.groups||[];S.edges=x.edges||[];S.title=x.title||'Imported Diagram';$('#docTitle').value=S.title;S.selected=null;$('#modalback').classList.remove('show');renderAll();setTimeout(fitView,30);showToast('Diagram imported')}catch(e){showToast('Invalid JSON')}};
 $('#themeBtn').onclick=()=>window.parent?.postMessage({source:'urage-tool',type:'tool:theme-request'},'*');$('#context').addEventListener('click',e=>{const a=e.target.dataset.act;if(!a)return;hideMenus();if(a==='duplicate')duplicateSelected();if(a==='delete')deleteSelected();if(a==='front')zMove(1);if(a==='back')zMove(-1);if(a==='connect'&&S.selected?.type==='node')startConnect(S.selected.id,0,0)});document.addEventListener('pointerdown',e=>{if(!e.target.closest('.context')&&!e.target.closest('#exportBtn'))hideMenus()});
 let resizeT;addEventListener('resize',()=>{clearTimeout(resizeT);resizeT=setTimeout(renderMini,100)});
}
let spaceDown=false;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){spaceDown=true;e.preventDefault()}if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected()}else if(e.key.toLowerCase()==='c')setMode('connect');else if(e.key.toLowerCase()==='f')fitView();else if(e.key==='Escape'){S.connect=null;$('#draftEdge').setAttribute('d','');setMode('select');clearSelection()}});document.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false});
init();
})();